services:
  db:
    image: postgres:17
    container_name: game-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: game-backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5000:5000"

networks:
  game-network:
    driver: bridge

volumes:
  pgdata:
    driver: local