"""llm token -> bot id

Revision ID: aca0d71c7f7e
Revises: 
Create Date: 2025-08-12 22:05:12.161950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca0d71c7f7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('moves_llm_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'bots', ['bot_id'], ['id'])
        batch_op.drop_column('llm_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('moves_llm_id_fkey'), 'bots', ['llm_id'], ['id'])
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###
