"""llm link not uniq

Revision ID: 769301aa013f
Revises: 305c81f566f5
Create Date: 2025-08-26 23:11:42.170633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769301aa013f'
down_revision = '305c81f566f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bots_llm_api_link_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('bots_llm_api_link_key'), ['llm_api_link'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
