services:
  db:
    image: postgres:17
    container_name: game-db
    env_file:
      - example.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  game-network:
    driver: bridge

volumes:
  pgdata:
    driver: local